export const APP_COLOR = {
  PRIMARY_COLOR: "#ee4d2d",
  SECONDARY_TEXT_COLOR: "#9796A1",
  WHITE_COLOR: "#FFFFFF",
  ERROR_COLOR: "#FF0000",
  BORDER_BUTTON_DEFAULT: "#d0d0d0",
  BORDER_BUTTON_ACTIVE: "#ee4d2d",
};
